services:
  nginx:
    build: 
      context: ./requirements/nginx
      args:
        SSL_KEY_DIR: ${SSL_KEY_DIR}    
        SSL_CERT_PATH: ${SSL_CERT_PATH} 
        SSL_SUBJ: ${SSL_SUBJ} 
        SSL_KEY_PATH: ${SSL_KEY_PATH} 
    image: nginx
    env_file:
      - .env
    restart: always
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - web_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - webnet
  
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks: 
      - webnet
  
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    container_name: wordpress
    volumes:
      - web_data:/var/www/html
    env_file:
      - .env
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - webnet

networks:
  webnet:
    name: webnet
    driver: bridge

volumes:
  web_data:
    name: web_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
