services:
  nginx:
    build: 
      context: ./requirements/nginx
      args:
        SSL_KEY_DIR: ${SSL_KEY_DIR}    
        SSL_CERT_PATH: ${SSL_CERT_PATH} 
        SSL_SUBJ: ${SSL_SUBJ} 
        SSL_KEY_PATH: ${SSL_KEY_PATH} 
    image: nginx
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      SSL_KEY_PATH: ${SSL_KEY_PATH} 
      SSL_CERT_PATH: ${SSL_CERT_PATH} 
    restart: always
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/${USER}/data/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - webnet
  
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /home/${USER}/data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks: 
      - webnet
  
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    container_name: wordpress
    volumes:
      - /home/${USER}/data/wordpress:/var/www/html
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
